Resources:
  SpaSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.siteName}-spa
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
