Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.siteName}-static
#      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  StaticSiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: StaticSiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Sid: StaticSiteBucketPublicAccess
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource:
              Fn::Join: ['', [Fn::GetAtt: [ StaticSiteBucket, Arn ], '/*'] ]
Outputs:
  StaticSiteBucketName:
    Value:
      Ref: StaticSiteBucket
