service: temedis-com-spa

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage}
  versionFunctions: false

plugins:
  - serverless-finch
  - serverless-domain-manager

custom:
  client:
    bucketName: ${opt:domain}.${self:provider.stage}.spa
    distributionFolder: web
    indexDocument: index.html
    errorDocument: index.html

  customDomain:
    domainName: ${self:provider.stage}.${opt:domain}
    certificateArn: ${opt:domain-cert}
    basePath: '/spa' # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true
